### ISSUE TITLE
Doesn't work on py2 anymore....

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/nbsphinx-feedstock#16]
nbsphinx version 0.4.* uses the "nonlocal" keyword -- and will not run on python2

This recipe is set to

noarch: python

So it is building for py2 and py3 -- apparently it will import in py2, and thus pass the tests, but not actually run.

The source setup.py has:

        'Programming Language :: Python',
        'Programming Language :: Python :: 3',

I can't remember how to suppress py2 building with noarch, but it can be done :-)

**Comment by kmuehlbauer** [comment]
@ChrisBarker-NOAA Thanks for spotting this. I'll take care of this within the next two hours.

In noarch you can suppress py2k by specifying python >= 3.6 in the build/host/run sections. It is mentioned in the cf-docs somewhere.

**Comment by mgeier** [comment]
Thanks y'all for your packaging efforts!

I just want to confirm that `nbsphinx` is not meant to be used with Python 2.
In fact, Sphinx itself needs at least Python 3.5, so anything below that doesn't make sense for `nbsphinx`.

**Comment by kmuehlbauer** [comment]
@mgeier Thanks for the confirmation. Hope that we have now fixed everything.

**Comment by mgeier** [comment]
I just realized that I've been releasing universal wheels up to now, but those should be Python-3-only, too, I guess.

This will take care of if for future releases: https://github.com/spatialaudio/nbsphinx/pull/268

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- not really the place for it, but the tools (both wheel building and conda packages) really should make it hard, rather than easy, to do this! (this being accidentally making a py2 package for a code that does not support py2)

**Comment by mgeier** [comment]
@ChrisBarker-NOAA In this case it's actually my fault. I've added a `setup.cfg` file to automatically generate "universal" wheels mostly without thinking, because I've added the same thing to other modules before (which actually want to be "universal").

The default for `bdist_wheel` is to create non-universal wheels.

I don't know about the conda process.

**Comment by ChrisBarker-NOAA** [comment]
The default for conda is to build both. "noarch" actually means no specific OS/processor architecture, AND no specific Python version :-(
